### ISSUE TITLE
Feature description to Shutdown and Kill the Whole Cluster

### ISSUE THREAD

**Issue by vanthome** [doxout/recluster#15]
Hi, I made a comparison of several similar modules such as [1]  [2] [3] [4] and I liked yours the most because it comes without bloat!

I think there are two more important use-case that should be described in README.md:

"To gracefully shutdown the whole cluster (workers and master)"

kill -s TERM <cluster_pid>

"To forcefully kill the whole cluster (workers and master)"

kill -s KILL <cluster_pid>

What do you think about adding it?

[1] https://github.com/strongloop/strong-cluster-control
[2] https://github.com/andrewrk/naught
[3] https://github.com/ql-io/cluster2
[4] https://github.com/Unitech/pm2

**Comment by Atinux** [comment]
I think you can close this issue @spion?

**Comment by spion** [comment]
Yeah, I'm not sure its necessary to add this to the README, but I'll reopen if there is a good argument for it.
