### ISSUE TITLE
Workers getting requests *after* `disconnect` message

### ISSUE THREAD

**Issue by dahjelle** [doxout/recluster#21]
Hi!

I'm trying to use `recluster` to get zero-downtown deploys for my `hapi` web server. It works most of the time, but sometimes I'm seeing a worker process that continues receiving and responding to requests even after it has been given a `disconnect` message. As far as I understand, `recluster` should not be routing requests to the old workers anymore?

In particular, I'm using `hapi` to proxy a CouchDB `_changes` feed, which is a longpoll feed that should last for 25 seconds at a shot. It is these longpolls that I'm primarily having an issue with.

I can see that the workers are still getting requests after the `disconnect` message, as I'm logging the `pid` when the `hapi` server receives requests and when it responds.

I'm directly running the following `cluster.js`:

```javascript
var recluster = require('recluster'),
    path = require('path');

var cluster = recluster(path.join(__dirname, 'index.js'), {
    timeout: 120, // seconds
    workers: 2,
    readyWhen: 'ready',
    log: {
        respawns: true
    }
});
cluster.run();

process.on('SIGUSR2', function() {
    console.log('Got SIGUSR2, reloading cluster...' + new Date());
    cluster.reload(function() {
        console.log("done reloading cluster");
    });
});

console.log("spawned cluster, kill -s SIGUSR2", process.pid, "to reload");
```

In my `hapi` server, I have:

```javascript
server.start( function () {
    	process.send({cmd: 'ready'});
        server.log('info', 'Server running at: ' + server.info.uri + ' with PID #' + process.pid + " at " + new Date() );
    });
```

And to handle the `disconnect` message:

```javascript
process.on('message', function(m) {
    if (m.cmd == 'disconnect') {
		// disconnected from master, no more clients. clean up.
		console.log("close message for PID#" + process.pid + " at " + new Date());
		server.stop({
			timeout: 60000
		}, function() {
			console.log('hapi stopped with PID#' + process.pid + " at " + new Date());
			process.exit();
		});
    }
});
```

I'm sorry I don't yet have a reduced test case; I can try work on one if you don't see anything immediately obviously wrong with my configuration. ;-)

**Comment by spion** [comment]
Thats unusual - are you receiving the disconnect messages in the worker process?

I don't see anything unusual with your configuration - it should be working just fine. What version of node/iojs are you using?

**Comment by dahjelle** [comment]
It turns out that `hapi` was only not accepting new *connections* but would accept new *requests* after `server.stop` (see hapijs/discuss#82 and hapijs/discuss#81 for some more info). They had a patch (hapijs/hapi#2363) to change this; once I applied that, everything worked as expected.

So it looks like it wasn't a `recluster` issue after all. Thanks for your help!
