### ISSUE TITLE
Access to internal workers array

### ISSUE THREAD

**Issue by asafyish** [doxout/recluster#22]
Hi,

It's not possible to do logging correctly without.
The problem is, each worker trying to log to the same file will fail because the file is locked.
The solution is to allow the cluster file do all the logging, but for that, he need to listen on the workers stdout and stderr.

See http://stackoverflow.com/questions/18841333/when-use-the-cluster-and-winston-in-nodejs-the-logs-maxsize-does-not-work

**Comment by spion** [comment]
You can use `cluster.on('online', function(worker) { ... })` to access each worker as it becomes ready and attach any listeners you like. The events are not documented yet, but I plan to add the docs soon.

**Comment by spion** [comment]
This is now also available via `cluster.workers()`
