### ISSUE TITLE
Is reload truly zero downtime?

### ISSUE THREAD

**Issue by thedug** [doxout/recluster#25]
If I'm reading the code correctly it is possible that the some requests could fail if they occur between shutdown and the fork loop at the end.

Douglas

**Comment by spion** [comment]
That part of the code only sets up the listeners to run after all replacements are ready - the kill instructions are run only then.

**Comment by thedug** [comment]
Yeah.. I realized my error and closed the ticket. :)

**Comment by frankLife** [comment]
@spion , I have been studying the recluster source code(amazing!) recently,but I can't make sense of backoff logic totally. can you send me your email to let me talk  my question to you :) 

my email: cquptzw@gmail.com
