### ISSUE TITLE
Does recluster module maintains sticky session

### ISSUE THREAD

**Issue by rohit-taneja** [doxout/recluster#26]
I just want to know that does recluster maintains sticky session or not i.e for example if user 1's first request went to the first worker then whether recluster ensures that the next subsequent requests will also go to the same first worker?

**Comment by spion** [comment]
I'm afraid not, requests are distributed to the workers by the system (or in case of 0.12 the round-robin scheduler included with the cluster module)

**Comment by rthealthkart** [comment]
Ok. Thanks.

**Comment by Ajaxy** [comment]
Okay, but how to support sessions then?

Particularly I'm intrested in socket.io support. I opened an issue there: https://github.com/socketio/socket.io/issues/2231

**Comment by spion** [comment]
Since 0.12 its possible to implement sticky sessions [as shown here](https://github.com/indutny/sticky-session)

I'll try to find the time to do it.

**Comment by spion** [comment]
Experimental support for sticky listening (in node v0.12 and later) is now available at

https://github.com/spion/sticky-listen
