### ISSUE TITLE
recluster.terminate() accepts a callback as argument

### ISSUE THREAD

**Issue by dodev** [doxout/recluster#33]
Hi!

I've been using your module for a while and I think it's doing its job very well and it has a small, adequate interface. Kudos!

I was refactoring one of my project's boot.js file (which is initiating a recluster instance and firing up the application) and I thought it would be very helpful to be able to execute code when the cluster terminates. Something like [this](https://github.com/dodev/recluster/commit/5e1dbeb4d041280356b54a9982cbf93a7788ea1f). That way you can assign handlers to standard terminating signals, in them you can terminate the cluster and when it's ready, exit the process. Like so:
```javascript
var cluster = recluster({....});

function shutdown() {
    cluster.terminate(process.exit);
}

process
    .on('SIGUSR2', cluster.reload)
    .on('SIGINT', shutdown)
    .on('SIGTERM', shutdown);

cluster.run();
```

I can send a pull request with the changes and tests, if you are interested.

**Comment by spion** [comment]
Thanks for the kind words. 

The idea sounds good to me! A PR would be awesome :)

**Comment by dodev** [comment]
So the feature is upstream, I'll close this feature request.
