### ISSUE TITLE
respawn and backoff with multiple workers

### ISSUE THREAD

**Issue by durkes** [doxout/recluster#36]
During testing, backoff seems to work properly with 1 worker, but with 4 workers, the backoff (max respawn time) is exceeding the set time.

For example:
var opt = {
	workers: 4,
	/*seconds*/
	timeout: 300,
	respwan: 2,
	backoff: 10
};

If the app is crashed repeatedly (for testing), the respawn time ends up being over 30 seconds and more, exceeding the 10 second backoff setting. I'll be happy to review the code to track down the problem, but I wanted to first make sure this was in fact a bug and not a misunderstanding on my part.

Thank you for a great module.

**Comment by spion** [comment]
The respawn delay is shown relative to the moment of crash, but the delay capped by `backoff` is the time after the latest scheduled respawn. Therefore if a respawn has already been scheduled 10s from now, the next respawn will be scheduled 20s from now to make space between them. If afterwards there is a 3rd respawn, it will be scheduled 30s from now (10s after the latest scheduled one).

**Comment by durkes** [comment]
Got it. It is working correctly then! Thank you
