### ISSUE TITLE
Daemon option

### ISSUE THREAD

**Issue by Atinux** [doxout/recluster#37]
Hi, I want to tell you that I really like your module and your work.

I use recluster for my project and I am really impressed :)

I would like to know if it's possible to add an option for launching recluster as a daemon or if I should use a node module for this?

I thought that maybe [start-stop-daemon](https://github.com/jiem/start-stop-daemon) could be a solution. I would love to know your opinion about it.

Thank you

**Comment by spion** [comment]
Hi!  

Thanks for the kind words!

Normally (on development machines and VPS) I use recluster together with https://github.com/spion/nac so I haven't found the need to directly daemonize the clustered process. 

If you need daemon functionality, feel free to use any module together with recluster, and/or publish a command line version. I think there was some work started in https://github.com/NineCollective/cluster-start - perhaps that could be a nice place to add daemonization.

**Comment by Atinux** [comment]
Thank you, I'm going to take a look at all of this!

I'm actually working on it on my project named [pjs](https://www.github.com/Atinux/pjs) and recluster already works like a charm! I'm looking for a way for doing `pjs start` to launch it as a daemon.

I'll keep you updated when I'll
find a solution.

Have a great day!
