### ISSUE TITLE
Respawn issue with two instances

### ISSUE THREAD

**Issue by tarmolov** [doxout/recluster#38]
If I add two instances of recluster and run both of them, respawning will work incorrectly.

```
$ git clone https://github.com/tarmolov/recluster-test-app.git
$ cd recluster-test-app
$ npm install
$ npm start
> recluster-test-app@0.0.1 start /Users/hevil/Yandex/recluster-test-app
> node server.js

app1
app2
/Users/tarmolov/recluster-test-app/app1.js:4
    throw new Error('Error in app1');
    ^

Error: Error in app1
    at Timeout.setTimeout (/Users/tarmolov/recluster-test-app/app1.js:4:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[71627] worker (0:1) must be replaced, respawning in 0
app2
```

The synthetic error is thrown in `app1` and I expect that the app1 will be respawned. However, It respawns `app2` instead.

**Comment by spion** [comment]
Due to limitations of node's cluster, you can only have one instance of recluster per master process.

I was hoping node would change this when I originally wrote recluster. Unfortunately they haven't done that.

**Comment by tarmolov** [comment]
It's sad :(

I'll close the issue then.
